config/routes.rb
LimewareMobilePortal::Application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  root :to => 'static_pages#home'
  match "/signin", to: 'sessions#new'
  match "/signout", to: 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
  LIME_EMAIL_REGEX = /\A[\w+\-.]+@(time4)?lime+\.com+\z/i
  validates :name, presence: true, length: {maximum: 50, minimum: 3}
  validates :email, presence: true, format: { with: LIME_EMAIL_REGEX, message: "is not a valid LIME email"},
            uniqueness: {case_sensitive: false}
  before_save :create_remember_token

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

  def self.ad_authenticate(user_name_or_email, password)
    if user_name_or_email.include? "@"
      user_name_or_email = user_name_or_email.split("@").first
    end
    if user_name_or_email.empty? || password.empty?
      raise ArgumentError, "User name/email or Password cannot be empty"
    else
      #authenticate against lime ad
      require "net/ldap"
      domain = APP_CONFIG[:domain]
      ldap = Net::LDAP.new
      ldap.host =  APP_CONFIG[:ldap_host]
      ldap.port = APP_CONFIG[:ldap_port]
      ldap.auth "#{domain}\\#{user_name_or_email}", "#{password}"
      ldap.bind
    end
  end
  def self.authorize(email,password  )
    find_by_email(email) if ad_authenticate(email,password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header>
	<div class="navbar navbar-fixed-top navbar-inverse" >
		<div class="navbar-inner">
			<%= link_to 'LIME Mobile Portal', root_path, {class: "brand"} %>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="well sidebar-nav">
    <ul class="nav nav-list">
        <li><%= link_to "Applications", '#' %></li>
        <li><%= link_to "Roles", '#' %></li>
        <li><%= link_to "Users", '#' %></li>
        <li><%= link_to "Logs", "#" %></li>
        <li><%= link_to "Sign Out", signout_path, method: "delete" %></li>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LimewareMobilePortal</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<legend>
			<h1>LIME Mobile Portal</h1>
		</legend>
		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
		<div class="container-fluid">
			<div class="row-fluid">
              <% if signed_in? %>
	    		<div class="span3">
    				<%= render 'layouts/sidebar'%>	
    			</div>
                <% end %>
    			<div class="span9">
    				<div class="hero-unit">
    					<%= yield %>
    				</div>      
    			</div>
  			</div>
  		</div>		
		<%= debug(params)  if Rails.env.development? %>
	</div>
</body>
</html>

app/views/static_pages/home.html.erb
<h1>Welcome to LMP</h1> 
<br>
<%= link_to "Sign In", signin_path, class: "offset5 btn btn-large btn-primary btn-inverse" %>